export const GAME_CONFIG = {
  width: 800,
  height: 600,
  player: {
    width: 56,
    height: 26,
    speed: 420,
    fireCooldownSeconds: 0.24,
    shootInputBufferSeconds: 0.12,
    movementGraceSeconds: 0.1,
    acceleration: 2800,
    deceleration: 2000,
    respawnFloatSeconds: 1.8,
    respawnFloatDistancePx: 36,
    recoilDistancePx: 4,
  },
  projectile: {
    width: 4,
    height: 12,
    speed: 480,
  },
  enemy: {
    rows: 4,
    columns: 9,
    width: 36,
    height: 24,
    horizontalGap: 18,
    verticalGap: 16,
    startX: 90,
    startY: 72,
    horizontalSpeed: 34,
    speedRampFactor: 0.9,
    descendStep: 18,
    scoreByRow: [40, 30, 20, 10],
  },
  enemyFire: {
    baseCooldownSeconds: 1.05,
    cooldownJitterSeconds: 0.4,
    hardModeMultiplier: 0.72,
  },
  waves: {
    total: 3,
  },
  countdownSeconds: 2.5,
  effects: {
    shakeDurationSeconds: 0.14,
    shakeMagnitudePx: 5,
    flashDurationSeconds: 0.1,
    particleBurstCount: 14,
    particleLifeSeconds: 0.35,
    playerHitShakeDurationSeconds: 0.3,
    playerHitShakeMagnitudePx: 9,
    playerHitParticleBurstCount: 36,
    playerHitParticleLifeSeconds: 0.85,
    playerHitParticleSpeedMin: 90,
    playerHitParticleSpeedMax: 220,
  },
  barrier: {
    count: 4,
    rows: 6,
    columns: 8,
    cellSize: 8,
    cellDurability: 2,
    startX: 110,
    startY: 430,
    spacing: 150,
  },
  visual: {
    enableCrtByDefault: false,
  },
  loseLineOffset: 70,
} as const;
